### ISSUE TITLE
Errors with PHP 5.4

### ISSUE THREAD

**Issue by Toutouwai** [netcarver/ModuleReleaseNotes#2]
Similar to [another issue](https://github.com/netcarver/ModuleReleaseNotes/issues/1) raised earlier...

The module is giving compile errors in PHP 5.4 due to the way empty() is used in the following lines:

https://github.com/netcarver/ModuleReleaseNotes/blob/c499c2bf58aec3d319e6e46297b1c140083e3c0f/GithubRepositoryAdaptor.php#L161

https://github.com/netcarver/ModuleReleaseNotes/blob/c499c2bf58aec3d319e6e46297b1c140083e3c0f/BitbucketRepositoryAdaptor.php#L113

https://github.com/netcarver/ModuleReleaseNotes/blob/c499c2bf58aec3d319e6e46297b1c140083e3c0f/ModuleReleaseNotes.module#L801

**Comment by netcarver** [comment]
@Toutouwai Thanks Robin. Working on this now.

**Comment by netcarver** [comment]
@Toutouwai Could you try [branch php54](https://github.com/netcarver/ModuleReleaseNotes/tree/php54) and let me know if that fixes things for you?

**Comment by Toutouwai** [comment]
Yep, that's fixed it. Thanks.

**Comment by netcarver** [comment]
Added to master and pushed this bugfix as release 0.10.8. Closing this issue, thank you!
