### ISSUE TITLE
CSS selectors too broad

### ISSUE THREAD

**Issue by Toutouwai** [netcarver/ModuleReleaseNotes#3]
Hi netcarver,

I noticed that this module autoloads on `"template=admin"`, which causes the module CSS and JS to be loaded on all admin pages. The CSS includes some quite broad selectors such as...

```css
.warning {
  text-align:center;
  padding: 3em;
  border:2px dashed #d28282;
}
```

...which have the potential to target elements in the admin that aren't related to the module.

Could the CSS selectors could be more targeted to the module, e.g. `#Inputfield_changes-wrapper .warning { ... }`?

And if the module only needs to modify ProcessModule maybe you could even consider making the autoload selector more specific: `"process=ProcessModule"`?

**Comment by netcarver** [comment]
@Toutouwai Robin, good points. Will look into it later today.

**Comment by netcarver** [comment]
@Toutouwai Please try version 0.11.1

**Comment by Toutouwai** [comment]
Great, thanks!

Just wondering if all of the items that need styling actually exist within the `.release-notes` div? If so you could prefix _all_ the selectors with `.release-notes` (as per the first set of selectors in the CSS file) which would greatly reduce the risk that they'll get applied to unrelated elements.

Recently I've started using SCSS stylesheets with my modules which makes it much easier to be specific with CSS without repeating yourself, e.g.

```scss
.my-module-wrapper {
    .my-element { }
    ...
}
```

I exclude `.scss` files in `gitignore` so they don't go into the repo (only the compiled CSS does) but that step isn't really necessary.

**Comment by Toutouwai** [comment]
Will close now because it's was the `.warning` selector that I was affected by and that's fixed now. Thanks again!
