### ISSUE TITLE
PHP 8.1 Deprecated: Function strftime() is deprecated in ModuleReleaseNotes.module:416

### ISSUE THREAD

**Issue by adrianbj** [netcarver/ModuleReleaseNotes#4]
Thanks @netcarver :)

**Comment by netcarver** [comment]
Fixed in [fc625d1](https://github.com/netcarver/ModuleReleaseNotes/commit/fc625d1ab48dca017c11fe47306abfc096b64172)

**Comment by adrianbj** [comment]
Thanks!
